apiVersion: v1
kind: Namespace
metadata:
  name: volsync-webui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volsync-webui
  namespace: volsync-webui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-webui
rules:
- apiGroups: ["replication.storage.io"]
  resources: ["replicationsources", "replicationdestinations"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "patch", "suspend", "resume"]