apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "volsync-webui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "volsync-webui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "volsync-webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "volsync-webui.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "volsync-webui.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}